networks:
    lamp-network:
        driver: bridge

services:
    web:
        build: .
        ports:
            - "80:80"
        depends_on:
            - mysql
        volumes:
            - .:/var/www/html
        networks:
            - lamp-network
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: lamp_db
        volumes:
            - ./mysql_data:/var/lib/mysql
        networks:
            - lamp-network
    phpmyadmin:
        image: phpmyadmin
        ports:
            - "8080:80"
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
        networks:
            - lamp-network
    composer:
        image: composer:latest
        volumes:
            - .:/app
        working_dir: /app
        networks:
            - lamp-network
        command: composer install
    node:
        image: node:latest
        volumes:
            - .:/app
        working_dir: /app
        networks:
            - lamp-network
        command: npm install
